###
GET http://localhost:4508/personal
###
GET http://localhost:4508/channel/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZ1bG9uZyIsInVwZGF0ZWRBdCI6IjIwMjItMDctMTRUMTA6MTk6MDIuOTI1WiIsImVtYWlsIjoidnVsb25ncHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODc5MzAxLCJleHAiOjE2NTk4Nzk5MDF9.Mc_OtjnTC_8efp3hEp3UN9CQ5mjetkhqOREeTL0dLvY

{
    "conversationId":"62efbeb4a42dbf33e8fd567c"
}

###
POST http://localhost:4508/channel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZ1bG9uZyIsInVwZGF0ZWRBdCI6IjIwMjItMDctMTRUMTA6MTk6MDIuOTI1WiIsImVtYWlsIjoidnVsb25ncHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODc5MzAxLCJleHAiOjE2NTk4Nzk5MDF9.Mc_OtjnTC_8efp3hEp3UN9CQ5mjetkhqOREeTL0dLvY

{
    "recipientIds":["62cf93bec319d67226d3e370","62cfe566e4fef4c35b9263a3"]
}
### login
POST http://localhost:4508/auth/login
Content-Type: application/json

{
    "username":"vulong",
    "password":"123123"
}
### reftoken
POST http://localhost:4508/auth/refreshToken
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvY2h2MTIiLCJwYXNzd29yZCI6IiQyYiQxMCRSaGxWYXU1VG5MUC9scWRhS2hBQVlPWHA2dDc4T0sxdXJLdTM1ejZUUXREc0h6c1lJSGdMZSIsInJvbGUiOiJpbml0IiwiaXNBY3RpdmUiOnRydWUsInVwZGF0ZWRBdCI6IjIwMjItMDctMTRUMDM6NTU6NDIuODc3WiIsImlhdCI6MTY1Nzc3OTUxNCwiZXhwIjoxNjU3Nzc5NTQ0fQ.h59feY039LErARTsdsFqwsBPZm8232EZ0_IPD5USEcs"
}

###register
POST http://localhost:4508/auth/register
Content-Type: application/json

{
    "username":"testspecuser",
    "password":"11223344",
    "email":"testerrr@gmail.com",
    "birth": "2022-08-03T20:45:29+07:00"
}

###forgotpw
POST http://localhost:4508/auth/forgotPassword
Content-Type: application/json

{
    "username":"hochv12"
}

###resetpw
POST http://localhost:4508/auth/reset
Content-Type: application/json

{
    "newPassword":"112233",
    "token":"eyJhbGciOiJTkwNjgzNTQsImV4cCI6MTY1OTA2OTI1NH0.3DPviZi5V7gqe0OC83UMIpQUSsD8hz0504D9NfY5k38"
}

###
GET http://localhost:4508/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZ1bG9uZyIsInVwZGF0ZWRBdCI6IjIwMjItMDctMTRUMTA6MTk6MDIuOTI1WiIsImVtYWlsIjoidnVsb25ncHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODg5MjY4LCJleHAiOjE2NTk4ODk4Njh9.-Y5J6TFabt4_SvHfZrOhty8vk0pZ4INqA8dqeCaNNnA