### login
POST http://localhost:4508/auth/login
Content-Type: application/json

{
    "username":"hochv133",
    "password":"hochv1334"
}
### reftoken
POST http://localhost:4508/auth/refreshToken
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvY2h2MTIiLCJwYXNzd29yZCI6IiQyYiQxMCRSaGxWYXU1VG5MUC9scWRhS2hBQVlPWHA2dDc4T0sxdXJLdTM1ejZUUXREc0h6c1lJSGdMZSIsInJvbGUiOiJpbml0IiwiaXNBY3RpdmUiOnRydWUsInVwZGF0ZWRBdCI6IjIwMjItMDctMTRUMDM6NTU6NDIuODc3WiIsImlhdCI6MTY1Nzc3OTUxNCwiZXhwIjoxNjU3Nzc5NTQ0fQ.h59feY039LErARTsdsFqwsBPZm8232EZ0_IPD5USEcs"
}

###register
POST http://localhost:4508/auth/register
Content-Type: application/json

{
    "username":"hochv123",
    "password":"123",
    "email":"testhive98765@gmail.com"
}

###forgotpw
POST http://localhost:4508/auth/forgotPassword
Content-Type: application/json

{
    "username":"hochv12"
}

###resetpw
POST http://localhost:4508/auth/reset
Content-Type: application/json

{
    "newPassword":"112233",
    "token":"eyJhbGciOiJTkwNjgzNTQsImV4cCI6MTY1OTA2OTI1NH0.3DPviZi5V7gqe0OC83UMIpQUSsD8hz0504D9NfY5k38"
}

###
GET http://localhost:4508/auth/test
Authorization: Bearer 