
POST http://localhost:4508/auth/login
Content-Type: application/json

{
    "username":"hochv",
    "password":"123"
}
###
POST http://localhost:4508/auth/refreshToken
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZ1bG9uZ3B0IiwicGFzc3dvcmQiOiJ2dWxvbmdwdCIsImlhdCI6MTY1NzYxNzUzOH0.aVQiGQ8HawcOKBJQXBId4U0N38Cptyzv46_UEmJyy7Y"
}

###
POST http://localhost:4508/auth/register
Content-Type: application/json

{
    "username":"hochv12",
    "password":"123"
}

###
GET http://localhost:4508/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvY2h2IiwicGFzc3dvcmQiOiIxMjMiLCJyb2xlIjoiYWRtaW4iLCJpc0FjdGl2ZSI6dHJ1ZSwidXBkYXRlZEF0IjoiMjAyMi0wNy0xMlQwNzo1MToyOC4wNDdaIiwiaWF0IjoxNjU3NjQyNjYxLCJleHAiOjE2NTc2NDI3ODF9.d7weHfs8mOk2QdA-eoZJK64X8C25ko6b3wVXjjcHAs4